### ISSUE TITLE
Help wanted to narrow down to a realistic goals project scope. 

### ISSUE THREAD

**Issue by marcelfarres** [brainhack-school2020/BHS-AuditoryMultimodal#4]
Yey! I found a lot of interesting publically available datasets more or less related to auditory cognition and emotions!

Now its time to come to the real world and see what is durable to do in 2 weeks trying to avoid frustration and sleep deprivation.  

I am having trouble to see if it is better to try to combine different datasets or just focus on one. If it is feasible to combine different datasets, how I can combine EEG+MRI / MRI+MRI? What metrics/info can be extracted that can be common between them (not all of them)? 

Any input/help/ideas reference will be welcome :)

Background -> I want to start working with this problem as my Ph.D. involve multiple task run in different modalities (EEG, MRI, behavioural), some of the tasks are done in all of them, but some others are modality-specific. I want to do more than correlations between them.

@pbellec @PeerHerholz

**Comment by PeerHerholz** [comment]
What would be important to mention/outline here is the specific goal of your BrainHack school project. A lot of the points you mentioned will depend on that.

**Comment by pbellec** [comment]
Just to recap what I suggested on our call. It sounds like you are better off selecting one dataset for fMRI and another for EEG, as you are not planning to use the two modalities jointly anyway. Also if the dataset is somewhat similar to the data you are thinking to acquire for your PhD that's a plus. I would also encourage you to work on a subset of a dataset with a limited number of subjects (N~10?) in the interest of keeping the processing time reasonable.

**Comment by PeerHerholz** [comment]
I second @pbellec's points.
